steps:
#Deploy container image to Cloud Run
- name: 'gcr.io/$PROJECT_ID/imdb'
  args: ['beta','run','deploy','imdb-2020','--image','gcr.io/$PROJECT_ID/imdb','--region','us-central1','--platform','managed','--alow-unauthenticated']
images:
       - gcr.io/$PROJECT_ID/imdb