version: '3'
services:
    app:
        build:
            context: app
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        environment: 
            - PORT=8080
        container_name: flask
        image: imdb_flask:latest
        volumes:
            - appdata:/var/www
        restart: unless-stopped
volumes:
    appdata:
        driver: local