version: '3'
services:

    app:
        build:
            context: app
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        environment: 
            - PORT=8080
        container_name: flask
        image: imdb_flask:latest
        volumes:
            - appdata:/var/www
        restart: unless-stopped
        
    mongodb:
        image: mongo:4.0.8
        container_name: mongodb
        restart: unless-stopped
        command: mongod --auth
        environment:
          MONGO_INITDB_ROOT_USERNAME: mongodbuser
          MONGO_INITDB_ROOT_PASSWORD: 123456
          MONGO_INITDB_DATABASE: flaskdb
          MONGODB_DATA_DIR: /data/db
          MONDODB_LOG_DIR: /dev/null
        volumes:
              - mongodbdata:/data/db

volumes:
    appdata:
        driver: local
    mongodbdata:
        driver: local