version: '3'
services:
    app:
        build:
            context: .
        ports:
            - "8080:8080"
        environment: 
            - PORT=8080
        container_name: imdb
        image: imdb:latest
        volumes:
            - .:/app
        restart: always